### ISSUE TITLE
Add Redux use case example and DevTools

### ISSUE THREAD

**Issue by isomoar** [chicoxyzzy/react-for-hipsters-boilerplate#28]
Really like this boilerplate, have used it several times. But I think it needs additional Redux functionality, namely creating sample action, reducer, store and appropriate directory structure. It will be good to include devtools too. Are going to complete this boilerplate with this?

**Comment by chicoxyzzy** [comment]
Glad to hear you like it.

Yes I want to provide minimal example + tests in near future. What devtools do you mean?

**Comment by isomoar** [comment]
I mean [these](https://github.com/gaearon/redux-devtools) devtools for Redux state and actions debugging.
